# Generated by Django 4.2.30 on 2026-07-16 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('file_type', models.CharField(choices=[('csv', 'CSV'), ('tsv', 'TSV'), ('json', 'JSON'), ('parallel', 'Parallel Files')], max_length=20)),
                ('total_pairs', models.IntegerField(default=0)),
                ('cleaned_pairs', models.IntegerField(default=0)),
                ('mongo_collection', models.CharField(help_text='MongoDB collection name for raw data', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('exploring', 'Exploring'), ('preprocessing', 'Preprocessing'), ('ready', 'Ready for Training'), ('training', 'Training'), ('completed', 'Completed')], default='uploaded', max_length=30)),
            ],
            options={
                'db_table': 'datasets',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PreprocessingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('original_shape', models.JSONField(default=dict, help_text='{"rows": N, "cols": N}')),
                ('dtypes_info', models.JSONField(default=dict)),
                ('sample_pairs', models.JSONField(default=list, help_text='First 10 sentence pairs')),
                ('encoding_notes', models.TextField(blank=True, default='')),
                ('duplicate_count_full', models.IntegerField(default=0, help_text='Duplicates on EN+AR pair')),
                ('duplicate_count_en', models.IntegerField(default=0, help_text='Duplicates on EN only')),
                ('duplicate_count_ar', models.IntegerField(default=0, help_text='Duplicates on AR only')),
                ('duplicate_pct', models.FloatField(default=0.0)),
                ('pairs_after_dedup', models.IntegerField(default=0)),
                ('missing_en_count', models.IntegerField(default=0)),
                ('missing_ar_count', models.IntegerField(default=0)),
                ('missing_en_pct', models.FloatField(default=0.0)),
                ('missing_ar_pct', models.FloatField(default=0.0)),
                ('pairs_after_missing', models.IntegerField(default=0)),
                ('outlier_count_zscore', models.IntegerField(default=0)),
                ('outlier_count_iqr', models.IntegerField(default=0)),
                ('outlier_pct', models.FloatField(default=0.0)),
                ('pairs_after_outliers', models.IntegerField(default=0)),
                ('length_ratio_min', models.FloatField(default=0.0)),
                ('length_ratio_max', models.FloatField(default=0.0)),
                ('chart_paths', models.JSONField(default=list, help_text='List of chart file paths')),
                ('imbalance_applicable', models.BooleanField(default=False)),
                ('class_distribution_before', models.JSONField(default=dict)),
                ('class_distribution_after', models.JSONField(default=dict)),
                ('final_pairs', models.IntegerField(default=0)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preprocessing_runs', to='api.dataset')),
            ],
            options={
                'db_table': 'preprocessing_runs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TranslationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_text', models.TextField()),
                ('translated_text', models.TextField()),
                ('model_used', models.CharField(max_length=255)),
                ('translation_time_ms', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'translation_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('model_name', models.CharField(default='Helsinki-NLP/opus-mt-en-ar', max_length=255)),
                ('batch_size', models.IntegerField(default=4)),
                ('gradient_accumulation', models.IntegerField(default=8)),
                ('learning_rate', models.FloatField(default=5e-05)),
                ('max_epochs', models.IntegerField(default=10)),
                ('fp16', models.BooleanField(default=True)),
                ('weight_decay', models.FloatField(default=0.01)),
                ('early_stopping_patience', models.IntegerField(default=3)),
                ('train_size', models.IntegerField(default=0)),
                ('val_size', models.IntegerField(default=0)),
                ('test_size', models.IntegerField(default=0)),
                ('best_epoch', models.IntegerField(blank=True, null=True)),
                ('best_val_loss', models.FloatField(blank=True, null=True)),
                ('best_val_bleu', models.FloatField(blank=True, null=True)),
                ('learning_curve_path', models.CharField(blank=True, default='', max_length=500)),
                ('model_checkpoint_path', models.CharField(blank=True, default='', max_length=500)),
                ('diagnosis', models.CharField(choices=[('overfitting', 'Overfitting'), ('underfitting', 'Underfitting'), ('well_fit', 'Well Fit'), ('unknown', 'Unknown')], default='unknown', max_length=30)),
                ('diagnosis_notes', models.TextField(blank=True, default='')),
                ('epoch_data', models.JSONField(default=list, help_text='[{epoch, train_loss, val_loss, val_bleu}]')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_jobs', to='api.dataset')),
                ('preprocessing_run', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.preprocessingrun')),
            ],
            options={
                'db_table': 'training_jobs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('bleu_score', models.FloatField(default=0.0)),
                ('chrf_score', models.FloatField(default=0.0)),
                ('ter_score', models.FloatField(default=0.0)),
                ('baseline_bleu', models.FloatField(default=0.0)),
                ('baseline_chrf', models.FloatField(default=0.0)),
                ('baseline_ter', models.FloatField(default=0.0)),
                ('example_translations', models.JSONField(default=list, help_text='[{source, reference, baseline_output, model_output}]')),
                ('meets_target', models.BooleanField(default=False)),
                ('target_notes', models.TextField(blank=True, default='')),
                ('training_job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='api.trainingjob')),
            ],
            options={
                'db_table': 'evaluation_results',
            },
        ),
    ]
